version: '3.8'
services:
  web: 
    build: . 
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL: ${DATABASE_URL}
      - REDIS_URL: ${REDIS_URL}
      - TRIMET_API_KE: ${TRIMET_API_KEY}
    depends_on:
      - db 
      - redis
  db:
  image: postgres:14
  environment:
    - POSTGRES_USER: ${postgres_user}
    - POSTGRES_PASSWORD: ${postgres_password}
    - POSTGRES_DB: ${postgres_db}
  volumes:
    - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
